version: '3.7'

services:
  nginx1:
    build: nginx
  wrk1:
    build: wrk
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
    links:
      - nginx1
  wrk2:
    build: wrk
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
    links:
      - nginx1
  wrk3:
    build: wrk
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
    links:
      - nginx1
